modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="magic_witchcraft"
version="release_1.0"
displayName="Magic Witchcraft"
credits="You aren't allowed to distribute this mod without my agreement ! See license for more infos."
displayURL="https://github.com/SiniKraft/MagicWitchcraft"
authors="SiniKraft"
description='''
A mysterious and magical mod !
'''

[[dependencies.magic_witchcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




