modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="magic_witchcraft"
version="snapschot_0.2"
displayName="Magic Witchcraft"
credits="You aren't allowed to distribute this mod without my agreement ! See license for more infos."
displayURL="https://github.com/SiniKraft/MagicWitchcraft"
authors="SiniKraft"
description='''
A mysterious and magical mod !
'''

[[dependencies.magic_witchcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"




