modLoader="javafml"
loaderVersion="[35,)"
license="Not specified"

[[mods]]
modId="magic_witchcraft"
version="1.1.1"
displayName="Magic Witchcraft"
credits="You aren't allowed to distribute this mod without my agreement ! See license for more infos."
displayURL="https://github.com/SiniKraft/MagicWitchcraft"
updateJSONURL="https://raw.githubusercontent.com/SiniKraft/MagicWitchcraft/master/update.json"
logoFile="logo.png"
authors="SiniKraft"
description='''
A mysterious and magical mod !
'''

[[dependencies.magic_witchcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"




