/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package fr.sinikraft.magicwitchcraft;

import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.common.registry.EntityEntry;
import net.minecraftforge.fml.common.network.simpleimpl.IMessageHandler;
import net.minecraftforge.fml.common.network.simpleimpl.IMessage;
import net.minecraftforge.fml.common.network.IGuiHandler;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.discovery.ASMDataTable;
import net.minecraftforge.fml.common.IWorldGenerator;
import net.minecraftforge.fml.common.IFuelHandler;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.client.event.ModelRegistryEvent;

import net.minecraft.world.storage.WorldSavedData;
import net.minecraft.world.gen.IChunkGenerator;
import net.minecraft.world.chunk.IChunkProvider;
import net.minecraft.world.biome.Biome;
import net.minecraft.world.World;
import net.minecraft.util.ResourceLocation;
import net.minecraft.potion.Potion;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Item;
import net.minecraft.entity.player.EntityPlayerMP;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.Random;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

import fr.sinikraft.magicwitchcraft.gui.GuiTeleporterInterface;
import fr.sinikraft.magicwitchcraft.gui.GuiTeleporterBeaconInterface;
import fr.sinikraft.magicwitchcraft.gui.GuiSpectralPowerInterface;
import fr.sinikraft.magicwitchcraft.gui.GuiSpectralPowerInfuserRecipe4;
import fr.sinikraft.magicwitchcraft.gui.GuiSpectralPowerInfuserRecipe3;
import fr.sinikraft.magicwitchcraft.gui.GuiSpectralPowerInfuserRecipe2;
import fr.sinikraft.magicwitchcraft.gui.GuiSpectralPowerInfuserRecipe1;
import fr.sinikraft.magicwitchcraft.gui.GuiSpectralFurnaceInterface;
import fr.sinikraft.magicwitchcraft.gui.GuiSpectralChestInterface;
import fr.sinikraft.magicwitchcraft.gui.GuiSolarPanelGUI;
import fr.sinikraft.magicwitchcraft.gui.GuiRightClickerInterface;
import fr.sinikraft.magicwitchcraft.gui.GuiMysteriousExtractorRecipe1;
import fr.sinikraft.magicwitchcraft.gui.GuiMysteriousExtractorGUI;
import fr.sinikraft.magicwitchcraft.gui.GuiMagicalEnergyGeneratorInterface;
import fr.sinikraft.magicwitchcraft.gui.GuiMagicalEnergyCubeInterface;
import fr.sinikraft.magicwitchcraft.gui.GuiMagicalCompressorGUI;
import fr.sinikraft.magicwitchcraft.gui.GuiEnergyCrystalChargerInterface;
import fr.sinikraft.magicwitchcraft.gui.GuiDimensionalSwitcherGUI;
import fr.sinikraft.magicwitchcraft.gui.GuiAutoBlockRemoverInterface;
import fr.sinikraft.magicwitchcraft.gui.GuiAtomicFusionerGUI;

public class ElementsMagicWitchcraft implements IFuelHandler, IWorldGenerator {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<Biome>> biomes = new ArrayList<>();
	public final List<Supplier<EntityEntry>> entities = new ArrayList<>();
	public final List<Supplier<Potion>> potions = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public ElementsMagicWitchcraft() {
		sounds.put(new ResourceLocation("magic_witchcraft", "honey_pops"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("magic_witchcraft", "honey_pops")));
	}

	public void preInit(FMLPreInitializationEvent event) {
		try {
			for (ASMDataTable.ASMData asmData : event.getAsmData().getAll(ModElement.Tag.class.getName())) {
				Class<?> clazz = Class.forName(asmData.getClassName());
				if (clazz.getSuperclass() == ElementsMagicWitchcraft.ModElement.class)
					elements.add((ElementsMagicWitchcraft.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(ElementsMagicWitchcraft.ModElement::initElements);
		this.addNetworkMessage(MagicWitchcraftVariables.WorldSavedDataSyncMessageHandler.class,
				MagicWitchcraftVariables.WorldSavedDataSyncMessage.class, Side.SERVER, Side.CLIENT);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}

	@Override
	public void generate(Random random, int chunkX, int chunkZ, World world, IChunkGenerator cg, IChunkProvider cp) {
		elements.forEach(element -> element.generateWorld(random, chunkX * 16, chunkZ * 16, world, world.provider.getDimension(), cg, cp));
	}

	@Override
	public int getBurnTime(ItemStack fuel) {
		for (ModElement element : elements) {
			int ret = element.addFuel(fuel);
			if (ret != 0)
				return ret;
		}
		return 0;
	}

	@SubscribeEvent
	public void onPlayerLoggedIn(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerLoggedInEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData mapdata = MagicWitchcraftVariables.MapVariables.get(event.player.world);
			WorldSavedData worlddata = MagicWitchcraftVariables.WorldVariables.get(event.player.world);
			if (mapdata != null)
				MagicWitchcraft.PACKET_HANDLER.sendTo(new MagicWitchcraftVariables.WorldSavedDataSyncMessage(0, mapdata),
						(EntityPlayerMP) event.player);
			if (worlddata != null)
				MagicWitchcraft.PACKET_HANDLER.sendTo(new MagicWitchcraftVariables.WorldSavedDataSyncMessage(1, worlddata),
						(EntityPlayerMP) event.player);
		}
	}

	@SubscribeEvent
	public void onPlayerChangedDimension(net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerChangedDimensionEvent event) {
		if (!event.player.world.isRemote) {
			WorldSavedData worlddata = MagicWitchcraftVariables.WorldVariables.get(event.player.world);
			if (worlddata != null)
				MagicWitchcraft.PACKET_HANDLER.sendTo(new MagicWitchcraftVariables.WorldSavedDataSyncMessage(1, worlddata),
						(EntityPlayerMP) event.player);
		}
	}
	private int messageID = 0;
	public <T extends IMessage, V extends IMessage> void addNetworkMessage(Class<? extends IMessageHandler<T, V>> handler, Class<T> messageClass,
			Side... sides) {
		for (Side side : sides)
			MagicWitchcraft.PACKET_HANDLER.registerMessage(handler, messageClass, messageID, side);
		messageID++;
	}
	public static class GuiHandler implements IGuiHandler {
		@Override
		public Object getServerGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			if (id == GuiMysteriousExtractorGUI.GUIID)
				return new GuiMysteriousExtractorGUI.GuiContainerMod(world, x, y, z, player);
			if (id == GuiDimensionalSwitcherGUI.GUIID)
				return new GuiDimensionalSwitcherGUI.GuiContainerMod(world, x, y, z, player);
			if (id == GuiMagicalCompressorGUI.GUIID)
				return new GuiMagicalCompressorGUI.GuiContainerMod(world, x, y, z, player);
			if (id == GuiSolarPanelGUI.GUIID)
				return new GuiSolarPanelGUI.GuiContainerMod(world, x, y, z, player);
			if (id == GuiAtomicFusionerGUI.GUIID)
				return new GuiAtomicFusionerGUI.GuiContainerMod(world, x, y, z, player);
			if (id == GuiSpectralPowerInterface.GUIID)
				return new GuiSpectralPowerInterface.GuiContainerMod(world, x, y, z, player);
			if (id == GuiSpectralChestInterface.GUIID)
				return new GuiSpectralChestInterface.GuiContainerMod(world, x, y, z, player);
			if (id == GuiRightClickerInterface.GUIID)
				return new GuiRightClickerInterface.GuiContainerMod(world, x, y, z, player);
			if (id == GuiAutoBlockRemoverInterface.GUIID)
				return new GuiAutoBlockRemoverInterface.GuiContainerMod(world, x, y, z, player);
			if (id == GuiEnergyCrystalChargerInterface.GUIID)
				return new GuiEnergyCrystalChargerInterface.GuiContainerMod(world, x, y, z, player);
			if (id == GuiMagicalEnergyGeneratorInterface.GUIID)
				return new GuiMagicalEnergyGeneratorInterface.GuiContainerMod(world, x, y, z, player);
			if (id == GuiMagicalEnergyCubeInterface.GUIID)
				return new GuiMagicalEnergyCubeInterface.GuiContainerMod(world, x, y, z, player);
			if (id == GuiTeleporterInterface.GUIID)
				return new GuiTeleporterInterface.GuiContainerMod(world, x, y, z, player);
			if (id == GuiTeleporterBeaconInterface.GUIID)
				return new GuiTeleporterBeaconInterface.GuiContainerMod(world, x, y, z, player);
			if (id == GuiSpectralFurnaceInterface.GUIID)
				return new GuiSpectralFurnaceInterface.GuiContainerMod(world, x, y, z, player);
			if (id == GuiMysteriousExtractorRecipe1.GUIID)
				return new GuiMysteriousExtractorRecipe1.GuiContainerMod(world, x, y, z, player);
			if (id == GuiSpectralPowerInfuserRecipe1.GUIID)
				return new GuiSpectralPowerInfuserRecipe1.GuiContainerMod(world, x, y, z, player);
			if (id == GuiSpectralPowerInfuserRecipe2.GUIID)
				return new GuiSpectralPowerInfuserRecipe2.GuiContainerMod(world, x, y, z, player);
			if (id == GuiSpectralPowerInfuserRecipe3.GUIID)
				return new GuiSpectralPowerInfuserRecipe3.GuiContainerMod(world, x, y, z, player);
			if (id == GuiSpectralPowerInfuserRecipe4.GUIID)
				return new GuiSpectralPowerInfuserRecipe4.GuiContainerMod(world, x, y, z, player);
			return null;
		}

		@Override
		public Object getClientGuiElement(int id, EntityPlayer player, World world, int x, int y, int z) {
			if (id == GuiMysteriousExtractorGUI.GUIID)
				return new GuiMysteriousExtractorGUI.GuiWindow(world, x, y, z, player);
			if (id == GuiDimensionalSwitcherGUI.GUIID)
				return new GuiDimensionalSwitcherGUI.GuiWindow(world, x, y, z, player);
			if (id == GuiMagicalCompressorGUI.GUIID)
				return new GuiMagicalCompressorGUI.GuiWindow(world, x, y, z, player);
			if (id == GuiSolarPanelGUI.GUIID)
				return new GuiSolarPanelGUI.GuiWindow(world, x, y, z, player);
			if (id == GuiAtomicFusionerGUI.GUIID)
				return new GuiAtomicFusionerGUI.GuiWindow(world, x, y, z, player);
			if (id == GuiSpectralPowerInterface.GUIID)
				return new GuiSpectralPowerInterface.GuiWindow(world, x, y, z, player);
			if (id == GuiSpectralChestInterface.GUIID)
				return new GuiSpectralChestInterface.GuiWindow(world, x, y, z, player);
			if (id == GuiRightClickerInterface.GUIID)
				return new GuiRightClickerInterface.GuiWindow(world, x, y, z, player);
			if (id == GuiAutoBlockRemoverInterface.GUIID)
				return new GuiAutoBlockRemoverInterface.GuiWindow(world, x, y, z, player);
			if (id == GuiEnergyCrystalChargerInterface.GUIID)
				return new GuiEnergyCrystalChargerInterface.GuiWindow(world, x, y, z, player);
			if (id == GuiMagicalEnergyGeneratorInterface.GUIID)
				return new GuiMagicalEnergyGeneratorInterface.GuiWindow(world, x, y, z, player);
			if (id == GuiMagicalEnergyCubeInterface.GUIID)
				return new GuiMagicalEnergyCubeInterface.GuiWindow(world, x, y, z, player);
			if (id == GuiTeleporterInterface.GUIID)
				return new GuiTeleporterInterface.GuiWindow(world, x, y, z, player);
			if (id == GuiTeleporterBeaconInterface.GUIID)
				return new GuiTeleporterBeaconInterface.GuiWindow(world, x, y, z, player);
			if (id == GuiSpectralFurnaceInterface.GUIID)
				return new GuiSpectralFurnaceInterface.GuiWindow(world, x, y, z, player);
			if (id == GuiMysteriousExtractorRecipe1.GUIID)
				return new GuiMysteriousExtractorRecipe1.GuiWindow(world, x, y, z, player);
			if (id == GuiSpectralPowerInfuserRecipe1.GUIID)
				return new GuiSpectralPowerInfuserRecipe1.GuiWindow(world, x, y, z, player);
			if (id == GuiSpectralPowerInfuserRecipe2.GUIID)
				return new GuiSpectralPowerInfuserRecipe2.GuiWindow(world, x, y, z, player);
			if (id == GuiSpectralPowerInfuserRecipe3.GUIID)
				return new GuiSpectralPowerInfuserRecipe3.GuiWindow(world, x, y, z, player);
			if (id == GuiSpectralPowerInfuserRecipe4.GUIID)
				return new GuiSpectralPowerInfuserRecipe4.GuiWindow(world, x, y, z, player);
			return null;
		}
	}
	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<Biome>> getBiomes() {
		return biomes;
	}

	public List<Supplier<EntityEntry>> getEntities() {
		return entities;
	}

	public List<Supplier<Potion>> getPotions() {
		return potions;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final ElementsMagicWitchcraft elements;
		protected final int sortid;
		public ModElement(ElementsMagicWitchcraft elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLInitializationEvent event) {
		}

		public void preInit(FMLPreInitializationEvent event) {
		}

		public void generateWorld(Random random, int posX, int posZ, World world, int dimID, IChunkGenerator cg, IChunkProvider cp) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		public void registerModels(ModelRegistryEvent event) {
		}

		public int addFuel(ItemStack fuel) {
			return 0;
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
